### ISSUE TITLE
BNO problem

### ISSUE THREAD

**Issue by 931436690** [Aharoni-Lab/Miniscope-DAQ-QT-Software#13]
Hi, with your open source code, our miniscopeV4 is working. Thank you very much.
But there are some problems. When miniscopeV4 is runing, one image corruption will make the BNO invalid, bnobuffer of PC software gets all 0. The video stream can recover from the image corruption because of isochronous mode. BNO data never recover from the image corruption, we don't know why, maybe the USB data protocol of BNO is blocked. Restarting the USB data protocol of BNO maybe is helpful to solve the problem, even though I don't know how to do it.
I think that the connector(U.FL-R-SMT) is too close to the L5(inductance of coaxial cable, near U.FL-R-SMT). With more time of using the camera, L5 make more heat， the conector has more chances of loose connection problem which leads to the image corruption. That's the possible reason why the BNO of camra starts normal and does't work a few minutes later. Direct soldering of coaxial cables without U.FL-R-SMT maybe is an option. We are not sure now.More tests are needed.
Best wishes!

**Comment by daharoni** [comment]
Hi,
Can you explain what you mean by "image corruption"? Do you mean just a frame drop or a complete disconnection of the video stream? It sounds like the Miniscope is losing power or getting disconnected for a bit. Currently, the software can recover but it doesn't resend the initialization commands to the Miniscope. This means the BNO never gets re-enabled. I should be able to fix this in the next release.
Concerning the placement of the U.FL connector and the large L5 inductor. Unfortunately these components need to be placed close together to effectively filter our DC power from noise and high bandwidth signal. We haven't experienced an issue with disconnects caused by heating of the U.FL connector but we will keep an eye out for this.
We did leave solder pads for directly soldering the coax cable to the PCB. Just remember, if you do this, to make sure to pre-bake the Rigid-Flex PCB before soldering.

**Comment by 931436690** [comment]
"image corruption" should be caused by Miniscope losing power or getting disconnected for a bit. The BNO  getting re-enabled should solve this problem.
Thank you for advice and attention. I'll change another  U.FL connector to do the test, maybe our first miniscopeV4 has some problems of connection.
Best wishes！

**Comment by 931436690** [comment]
With your advice, I solve the problem，in which bnobuffer of PC software gets all 0. In  sendNewFrame() code of miniscope.cpp, I add such code:
       if (m_headOrientationStreamState) {
            if (bnoBuffer[f*5+0]==0 && bnoBuffer[f*5+1]==0 && bnoBuffer[f*5+2]==0 &&bnoBuffer[f*5+3] ==0)
            {
                    sendInitCommands();
            }
          ////////////only one condition, one line of code
       }

Thank you very much.

**Comment by daharoni** [comment]
Thanks for posting a fix to this issue. I will incorporate it in a future release.
