### ISSUE TITLE
Check file.open() return value when software attempts opens device config file.

### ISSUE THREAD

**Issue by jonnew** [Aharoni-Lab/Miniscope-DAQ-QT-Software#22]
https://github.com/Aharoni-Lab/Miniscope-DAQ-QT-Software/blob/cfecd42335b9b8bc955a3c65433c01e64ce44f3e/source/miniscope.cpp#L282

I'm debugging in Visual studio which uses a different build location, and the software is non-functional because the relative position between the config file and the executable is fixed (see line referenced above). This is not great, but the software should probably at least check the return code of `file.open` rather than just proceeding with an empty json object and then crashing.

**Comment by daharoni** [comment]
Thanks for the suggestion @jonnew. I'll add a check to the return code of file.open in the next release.

**Comment by daharoni** [comment]
Have added some error tracking when VideoDevice objects great created and initialized. Software now shows an error if the device config file(s) can't be opened and software doesn't crash due to this any more. Will work on using this error tracking for more errors in the future. d84736f9e37d3e851d7ac4b83e2a343da5445482 shows the relevant changes.
