### ISSUE TITLE
Switching DAQ to the externally triggerable state externally?

### ISSUE THREAD

**Issue by bastak** [Aharoni-Lab/Miniscope-DAQ-QT-Software#47]
Hello! Thanks you very much for your work! I am trying to implement the miniscope recordings via the external software (Labview), however I have the problem of not receiving the frame signal from the DAQ when I send the external start of the recording trigger signal. I guess this is because DAQ should be in the externally triggerable state that one can activate from the Miniscope QT software. I wonder is there some USB command that switches DAQ into this state, so I could reproduce the same command in Labview (and start to receiving frame signal upon the external triggering of the recording)? So far I found that the only USB command that is sent during toggling from QT software is resetting led to 0. Thanks!

**Comment by daharoni** [comment]
Hi @bastak, just to make sure I understand you correctly, you would like a way to send a command over USB to the Miniscope DAQ PCB to tell it that recording has started so that it begins outputting its sync signal from one of its SMA connectors?

If this is correct, then yes this is already implemented but in a somewhat indirect way, as is the case with all configuration commands to the DAQ, since we need to pack custom commands within the UVC protocol. To tell the DAQ recording has started/stopped you need to send a 1/0 over the Saturation UVC control channel. To see how this is implemented in the DAQ firmware, check out uvc.c (https://github.com/Aharoni-Lab/Miniscope-DAQ-Cypress-firmware/blob/master/Minisceop_DAQ/uvc.c) and search for "recording" variable.

`
else if (wValue == CY_FX_UVC_PU_SATURATION_CONTROL) {
    recording = ((glEp0Buffer[0]&RECORD_STATUS_MASK) == 1) ;
}
`

**Comment by bastak** [comment]
Yes, you understood correctly. Thank you very much, this is exactly what is was searching for! I'll try it
